#ifndef PYVERSION
#define PYVERSION "UNKOWN"
#endif // !PYVERSION

#ifndef SYSTEM_NAME
#define SYSTEM_NAME "UNKOWN"
#endif // !SYSTEM_NAME

#ifndef SYSTEM_VERSION
#define SYSTEM_VERSION "UNKOWN"
#endif // !SYSTEM_VERSION

#ifndef COMPILE_TIME
#define COMPILE_TIME "UNKOWN"
#endif // !COMPILE_TIME

// Print on compile time
#pragma message(PRINT_MACRO_NAME_VALUE(COLOR_NUM))
#pragma message(PRINT_MACRO_NAME_VALUE(BOARD_SIZE))
#pragma message(PRINT_MACRO_NAME_VALUE(COMING_CHESS_NUM))
#pragma message(PRINT_MACRO_NAME_VALUE(MIN_ELEMINATABLE_NUM))
#pragma message(PRINT_MACRO_NAME_VALUE(INVALID_MOVE_PENALTY))
#pragma message(PRINT_MACRO_NAME_VALUE(EACH_CHESS_ELEMINATED_REWARD))
#pragma message(PRINT_MACRO_NAME_VALUE(CHESS_NUM))
#pragma message(PRINT_MACRO_NAME_VALUE(POTENTIAL_MOVE_NUM))

#ifdef PYVERSION
#pragma message(PRINT_MACRO_NAME_VALUE(PYVERSION))
#endif // PYVERSION

#ifdef SYSTEM_NAME
#ifdef SYSTEM_VERSION
#pragma message(PRINT_MACRO_NAME_VALUE(SYSTEM_NAME))
#pragma message(PRINT_MACRO_NAME_VALUE(SYSTEM_VERSION))
#endif // SYSTEM_VERSION
#endif // SYSTEM_NAME

#ifdef COMPILE_TIME
#pragma message(PRINT_MACRO_NAME_VALUE(COMPILE_TIME))
#endif // COMPILE_TIME